language: python
python:
  - "3.5" #versão do python
env:
  - SECRET_KEY='s7zw!j_b2yd=d9p7^cdmh1^5%br4+c_ha9@^4a+p!e@=atj7nb' DEBUG=True ALLOWED_HOSTS=127.0.0.1 #Configuração das variáveis de ambiente
install:
  - pip install -r requirements.txt
script: #comandos a serem executados para realizar o teste
  - python manage.py check
  - python manage.py test
